version: '3.8'

services:
  # Main agent server
  alfred-agent:
    build: 
      context: ./agent-core
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/alfred
      - MODEL_PROVIDER=anthropic
      - MODEL_NAME=claude-3-5-sonnet-20241022
    depends_on:
      - postgres
    volumes:
      - ./agent-core:/app
    restart: unless-stopped

  # PostgreSQL database
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=alfred
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Memory MCP Server
  memory-mcp:
    build:
      context: ./mcp-servers/memory
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/alfred
    restart: unless-stopped

  # Official MCP Servers
  # Time MCP Server
  time-mcp:
    image: mcp/time
    ports:
      - "3001:3000"
    restart: unless-stopped

  # GitHub Personal MCP Server
  github-personal-mcp:
    image: mcp/github
    ports:
      - "3002:3000"
    environment:
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_TOKEN}
    restart: unless-stopped

  # GitHub Work MCP Server
  github-work-mcp:
    image: mcp/github
    ports:
      - "3003:3000"
    environment:
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_WORK_TOKEN}
    restart: unless-stopped

  # Fetch MCP Server
  fetch-mcp:
    image: mcp/fetch
    ports:
      - "3004:3000"
    restart: unless-stopped

  # Notion MCP Server
  notion-mcp:
    image: mcp/notion
    ports:
      - "3005:3000"
    environment:
      - NOTION_TOKEN=${NOTION_TOKEN}
    restart: unless-stopped

  # Sequential Thinking MCP Server
  sequential-thinking-mcp:
    image: mcp/sequentialthinking
    ports:
      - "3006:3000"
    restart: unless-stopped

  # Filesystem MCP Server
  filesystem-mcp:
    image: mcp/filesystem
    ports:
      - "3007:3000"
    volumes:
      - ./data:/data:rw
    restart: unless-stopped

  # Playwright MCP Server
  playwright-mcp:
    image: mcp/playwright
    ports:
      - "3008:3000"
    restart: unless-stopped

  # Memory MCP Server (Official)
  memory-mcp-official:
    image: mcp/memory
    ports:
      - "3009:3000"
    restart: unless-stopped

  # Atlassian MCP Server (Confluence + JIRA)
  atlassian-mcp:
    image: ghcr.io/sooperset/mcp-atlassian:latest
    ports:
      - "3010:3000"
    environment:
      - CONFLUENCE_URL=${CONFLUENCE_URL}
      - CONFLUENCE_USERNAME=${ATLASSIAN_USERNAME}
      - CONFLUENCE_API_TOKEN=${ATLASSIAN_API_TOKEN}
      - JIRA_URL=${JIRA_URL}
      - JIRA_USERNAME=${ATLASSIAN_USERNAME}
      - JIRA_API_TOKEN=${ATLASSIAN_API_TOKEN}
    restart: unless-stopped

  # Web interface (Next.js PWA)
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://alfred-agent:8080
    depends_on:
      - alfred-agent
    restart: unless-stopped

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - alfred-agent
      - web
    restart: unless-stopped

volumes:
  postgres_data: